### ISSUE TITLE
Error when trying to docker compose up

### ISSUE THREAD

**Issue by brunocasarotti** [DefiantLabs/cosmos-indexer#107]
Hi, I am trying to index sei chain but when I execute docker compose up it gives me an error:
Failed to execute. Err: base.start-block must be set when index-chain is enabled

here is my docker compose:

```
version: "3.9"

services:
  postgres:
    restart: "unless-stopped"
    image: postgres:15-alpine
    stop_grace_period: 1m
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=your_postgres_password
      - POSTGRES_USER=user123
      - POSTGRES_DB=mydbtest
    ports:
      - 5432:5432/tcp
    healthcheck:
      test: ["CMD", "nc", "-z", "-v", "localhost", "5432"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      default:
        aliases:
          - cosmos-indexer

  indexer:
    restart: "no"
    build:
      dockerfile: Dockerfile
    user: cosmos-indexer
    stop_grace_period: 10s
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    networks:
      default:
        aliases:
          - cosmos-indexer
    environment:
      - EXTENDED_ARGS="--base.index-chain"
      - LOG_LEVEL="info"
    command:
    - /bin/sh
    - -c
    - |
      cosmos-indexer index \
      --log.pretty = true \
      --log.level = debug \
      --base.index-transactions=true \
      --base.index-block-events=true \
      --base.start-block 0 \
      --base.end-block 10000000 \
      --base.throttling 1.00 \
      --base.rpc-workers=1 \
      --base.reindex=false \
      --base.reattempt-failed-blocks=false \
      --probe.rpc=https://sei-rpc.publicnode.com:443 \
      --probe.account-prefix=sei \
      --probe.chain-id=4444 \
      --probe.chain-name=sei \
      --database.host=postgres \
      --database.database=mydbtest \
      --database.user=user123 \
      --database.password=your_postgres_password \
      ${EXTENDED_ARGS}

volumes:
  postgres:
```
